<?php
namespace App\Http\Controllers;
use App\Http\Requests\AppointmentRequest; use App\Models\{Appointment,Pet,Vet}; use App\Services\AppointmentService; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Carbon\Carbon;
class AppointmentController extends Controller {
 public function index(Request $r){$u=$r->user();$q=Appointment::with(['pet','vet.user'])->when($u->role==='owner',fn($q)=>$q->where('user_id',$u->id))->when($u->role==='vet',fn($q)=>$q->where('vet_id',$u->vetProfile?->id));return $q->latest('starts_at')->paginate(20);}
 public function store(AppointmentRequest $r,AppointmentService $service){$pet=Pet::findOrFail($r->pet_id);abort_unless($pet->user_id===$r->user()->id,403);$vet=Vet::findOrFail($r->vet_id);abort_unless($vet->is_available,422,'Veterinarian is not accepting appointments.');$start=Carbon::parse($r->starts_at);$end=Carbon::parse($r->ends_at);$service->ensureAvailable($vet,$start,$end);$data=$r->validated()+['user_id'=>$r->user()->id,'status'=>'scheduled'];return response()->json(Appointment::create($data),201);}
 public function show(Request $r,Appointment $appointment){$u=$r->user();$allowed=$u->role==='admin'||$appointment->user_id===$u->id||($u->role==='vet'&&$appointment->vet_id===$u->vetProfile?->id);abort_unless($allowed,403);return $appointment->load(['pet.healthRecords','vet.user']);}
 public function update(Request $r,Appointment $appointment){$u=$r->user();$owner=$appointment->user_id===$u->id;$vet=$u->role==='vet'&&$appointment->vet_id===$u->vetProfile?->id;abort_unless($u->role==='admin'||$owner||$vet,403);$rules=['status'=>['sometimes',Rule::in(['scheduled','confirmed','completed','cancelled','no_show'])]];if($vet||$u->role==='admin')$rules+=['diagnosis'=>'nullable|string|max:5000','medication'=>'nullable|string|max:5000','follow_up_notes'=>'nullable|string|max:5000'];$appointment->update($r->validate($rules));return $appointment->fresh();}
 public function destroy(Request $r,Appointment $appointment){$u=$r->user();abort_unless($u->role==='admin'||$appointment->user_id===$u->id||($u->role==='vet'&&$appointment->vet_id===$u->vetProfile?->id),403);$appointment->update(['status'=>'cancelled']);return response()->noContent();}
}
